import os
from google.oauth2 import service_account
import dj_database_url
from dotenv import load_dotenv

# Cargar variables de entorno desde .env (solo si existe)
load_dotenv()

"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "insecure-local-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
     'rest_framework.authtoken',# Add Django REST Framework
    'drf_spectacular',
    'sede', # Mover sede al principio de las apps personalizadas
    'empleados',
    'usuarios',
    'mantenimientos',
    'inventory',      # Add your inventory app
    'storages',       # Google Cloud Storage
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # <-- AÑADE ESTA LÍNEA
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware', # Comentado temporalmente para depuración de "Unsupported Media Type"
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'inventory.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get(
            "DATABASE_URL",
            "postgresql://dummy:dummy@localhost:5432/dummy"
        ),
        conn_max_age=600,
        ssl_require=not DEBUG  # Solo requiere SSL en producción (cuando DEBUG es False)
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ]
}

# Configuración de CORS
CORS_ALLOW_ALL_ORIGINS = True # Permitir acceso desde cualquier dominio (Vercel, Localhost, etc.)
CORS_ALLOW_CREDENTIALS = True


# Media Files Settings
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'

import json

# Google Cloud Storage Settings
GS_BUCKET_NAME = 'equipos_inegra'
GS_PROJECT_ID = 'sunlit-analyst-448516-p8'

# Intentar leer desde variable de entorno (Producción) o desde archivo (Local)
google_creds_json = os.environ.get('GOOGLE_CREDENTIALS_JSON')

if google_creds_json:
    # En producción (Render/Railway), pegaremos el contenido del JSON en esta variable
    creds_dict = json.loads(google_creds_json)
    GS_CREDENTIALS = service_account.Credentials.from_service_account_info(creds_dict)
else:
    # En local, intentamos usar el archivo si existe
    cred_path = os.path.join(BASE_DIR, 'secrets', 'sunlit-analyst-448516-p8-152875467474.json')
    if os.path.exists(cred_path):
        GS_CREDENTIALS = service_account.Credentials.from_service_account_file(cred_path)
    else:
        # Si no hay variable de entorno ni archivo, lo dejamos como None para evitar errores de arranque
        GS_CREDENTIALS = None
        print("Aviso: No se encontraron credenciales de Google Cloud (Variable de entorno o archivo local).")

DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.gcloud.GoogleCloudStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Las URLs de los archivos ahora vendrán de Google Cloud
MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'

# Configuración de Drf-Spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'Integra API',
    'DESCRIPTION': 'Documentación de la API de Gestión de Equipos',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

