# Generated by Django 5.2.8 on 2026-01-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_historialempleado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialEmpleado',
        ),
    ]
