# Generated by Django 5.2.8 on 2026-01-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_delete_historialempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Retiro'),
        ),
    ]
