# Generated by Django 5.2.8 on 2026-01-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_empleado_ciudad_empleado_fecha_ingreso_and_more'),
        ('sede', '0003_delete_historialsede'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='sede.sede'),
        ),
    ]
