# Generated by Django 5.2.8 on 2026-01-13 21:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], max_length=50)),
                ('estado_mantenimiento', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50)),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('descripcion_problema', models.TextField(blank=True, help_text='Qué problema presentaba el equipo')),
                ('acciones_realizadas', models.TextField(blank=True, help_text='Qué se hizo durante el mantenimiento')),
                ('repuestos_utilizados', models.TextField(blank=True)),
                ('evidencia', models.FileField(default='', upload_to='evidencias_mantenimiento/')),
                ('evidencia_finalizacion', models.FileField(blank=True, null=True, upload_to='evidencias_mantenimiento/')),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimientos', to='inventory.equipo')),
                ('responsable', models.ForeignKey(blank=True, help_text='Técnico que realiza el mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sede.sede')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('equipo',), name='unique_maintenance_per_equipo')],
            },
        ),
    ]
