# Generated by Django 4.2.7 on 2024-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mantenimiento',
            name='unique_maintenance_per_equipo',
        ),
        migrations.AddConstraint(
            model_name='mantenimiento',
            constraint=models.UniqueConstraint(condition=models.Q(estado_mantenimiento__in=['Pendiente', 'En proceso']), fields=('equipo',), name='unique_pending_or_in_process_maintenance_per_equipo'),
        ),
    ]
