# Generated by Django 5.2.8 on 2026-01-20 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_alter_mantenimiento_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='evidencia',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='evidencia_finalizacion',
        ),
        migrations.CreateModel(
            name='EvidenciaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias_mantenimiento/')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='mantenimientos.mantenimiento')),
            ],
        ),
    ]
