# Generated by Django 5.2.8 on 2026-01-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0003_remove_mantenimiento_evidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='evidencia_finalizacion',
            field=models.FileField(blank=True, null=True, upload_to='evidencias_finalizacion/'),
        ),
    ]
