# Generated by Django 5.2.8 on 2026-01-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0004_mantenimiento_evidencia_finalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='evidencia_finalizacion',
            field=models.FileField(blank=True, help_text='Evidencia de finalización del mantenimiento', null=True, upload_to='evidencias_finalizacion/'),
        ),
    ]
