# Generated by Django 5.2.8 on 2026-01-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0005_alter_mantenimiento_evidencia_finalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_real_finalizacion',
            field=models.DateField(blank=True, help_text='Fecha en la que realmente se marcó como finalizado', null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, help_text='Fecha límite estimada', null=True),
        ),
    ]
