# Generated by Django 5.2.8 on 2026-01-13 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('sede', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='Serial')),
                ('ram', models.CharField(blank=True, max_length=20, null=True, verbose_name='Memoria RAM')),
                ('rom', models.CharField(blank=True, max_length=20, null=True, verbose_name='Almacenamiento (ROM)')),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operativo')),
                ('procesador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador')),
                ('antivirus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antivirus Instalado')),
                ('usuarios_sistema', models.TextField(blank=True, null=True, verbose_name='Usuarios del Sistema Operativo')),
                ('tipo_equipo', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Servidor', 'Servidor'), ('Tablet', 'Tablet'), ('Movil', 'Movil'), ('Otro', 'Otro')], default='Desktop', max_length=50, verbose_name='Tipo de Equipo')),
                ('redes_conectadas', models.TextField(blank=True, null=True, verbose_name='Redes Conectadas')),
                ('estado_tecnico', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Funcional', 'Funcional'), ('Con fallas', 'Con fallas'), ('Dañado', 'Dañado'), ('Desguazado', 'Desguazado'), ('En reparación', 'En reparación')], default='Funcional', max_length=50, verbose_name='Estado Técnico')),
                ('estado_disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('Reservado', 'Reservado'), ('No disponible por daño', 'No disponible por mantenimiento')], default='Disponible', max_length=50, verbose_name='Estado de Disponibilidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_entrega_a_colaborador', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega a Colaborador')),
                ('fecha_recibido_satisfaccion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Recibo')),
                ('firma_recibido_usuario', models.TextField(blank=True, null=True, verbose_name='Firma de Recibido del Colaborador')),
                ('nombre_jefe', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Jefe Inmediato')),
                ('cargo_jefe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Jefe Inmediato')),
                ('firma_recibido_jefe', models.TextField(blank=True, null=True, verbose_name='Firma de Recibido del Jefe')),
                ('firma_compromiso', models.TextField(blank=True, null=True, verbose_name='Firma de Compromiso')),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Fecha del Último Mantenimiento')),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Fecha del Próximo Mantenimiento')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas Internas (TI)')),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='empleados.empleado', verbose_name='Empleado Asignado')),
                ('responsable_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_entregados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la Entrega (TI)')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sede.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo Modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('tipo_accion', models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado')], max_length=20, verbose_name='Tipo de Acción')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='inventory.equipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Equipo',
                'verbose_name_plural': 'Historial de Equipos',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia', models.CharField(choices=[('Sistema Operativo', 'Sistema Operativo'), ('Office', 'Office'), ('Otro', 'Otro')], max_length=50)),
                ('tipo_activacion', models.CharField(choices=[('Original', 'Original'), ('Pirateada', 'Pirateada'), ('OEM', 'OEM'), ('Volumen', 'Volumen')], max_length=50)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_instalacion', models.DateField()),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Vencida', 'Vencida')], default='Activa', max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('equipo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='inventory.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Pasisalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Con Pendientes', 'Con Pendientes'), ('Rechazado', 'Rechazado')], max_length=50)),
                ('detalles_pendientes', models.TextField(blank=True, help_text='Detalles de equipos, periféricos o mantenimientos pendientes.', null=True)),
                ('pdf_url', models.URLField(blank=True, help_text='URL del PDF del pasisalvo generado.', max_length=500, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasisalvos_generados', to='empleados.empleado')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasisalvos_creados_por_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paz y Salvo',
                'verbose_name_plural': 'Paz y Salvos',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o descripción del periférico, ej: Mouse Logitech G203', max_length=100)),
                ('tipo', models.CharField(choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Base', 'Base'), ('Cargador', 'Cargador'), ('Monitor', 'Monitor'), ('Otro', 'Otro')], max_length=50)),
                ('estado_tecnico', models.CharField(choices=[('Funcional', 'Funcional'), ('Con fallas', 'Con fallas'), ('Dañado', 'Dañado')], default='Funcional', max_length=50)),
                ('estado_disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('Devuelto', 'Devuelto')], default='Disponible', max_length=50)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perifericos_asignados', to='empleados.empleado')),
                ('equipo_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perifericos', to='inventory.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPeriferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('observacion_devolucion', models.TextField(blank=True, null=True, verbose_name='Observación de Devolución')),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado', verbose_name='Empleado Asignado')),
                ('equipo_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipo', verbose_name='Equipo Asociado en la Entrega')),
                ('periferico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventory.periferico')),
            ],
            options={
                'verbose_name': 'Historial de Periférico',
                'verbose_name_plural': 'Historial de Periféricos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
