# Generated by Gemini on 2026-01-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialequipo',
            name='equipo_str',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipo (texto)'),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios', to='inventory.equipo'),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='tipo_accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado'), ('ELIMINADO', 'Eliminado')], max_length=20, verbose_name='Tipo de Acción'),
        ),
    ]
