# Generated by Gemini on 2026-01-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_historialequipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialperiferico',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'Historial de Asignación de Periférico', 'verbose_name_plural': 'Historial de Asignaciones de Periféricos'},
        ),
        migrations.AddField(
            model_name='historialperiferico',
            name='periferico_str',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Periferico (texto)'),
        ),
        migrations.AlterField(
            model_name='historialperiferico',
            name='periferico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_asignacion', to='inventory.periferico'),
        ),
        migrations.CreateModel(
            name='HistorialCambiosPeriferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periferico_str', models.CharField(blank=True, max_length=200, null=True, verbose_name='Periferico (texto)')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo Modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('tipo_accion', models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado'), ('ELIMINADO', 'Eliminado')], max_length=20, verbose_name='Tipo de Acción')),
                ('periferico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cambios', to='inventory.periferico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Cambios de Periférico',
                'verbose_name_plural': 'Historial de Cambios de Periféricos',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
