# Generated by Django 5.2.8 on 2026-01-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_periferico_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialperiferico',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'Historial de Periférico', 'verbose_name_plural': 'Historial de Periféricos'},
        ),
        migrations.RemoveField(
            model_name='historialequipo',
            name='equipo_str',
        ),
        migrations.RemoveField(
            model_name='historialperiferico',
            name='periferico_str',
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='inventory.equipo'),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='tipo_accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado')], max_length=20, verbose_name='Tipo de Acción'),
        ),
        migrations.AlterField(
            model_name='historialperiferico',
            name='periferico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventory.periferico'),
        ),
        migrations.DeleteModel(
            name='HistorialCambiosPeriferico',
        ),
    ]
