# Generated by Django 5.2.8 on 2026-01-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_equipo_estado_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialperiferico',
            name='es_baja',
            field=models.BooleanField(default=False, verbose_name='Fue dado de baja'),
        ),
        migrations.AddField(
            model_name='historialperiferico',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='historialperiferico',
            name='periferico_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Periférico (Histórico)'),
        ),
        migrations.AlterField(
            model_name='historialperiferico',
            name='periferico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='inventory.periferico'),
        ),
    ]
