# Generated by Django 5.2.8 on 2026-01-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_historialperiferico_es_baja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialperiferico',
            name='periferico_tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Periférico (Histórico)'),
        ),
    ]
