# Generated by Django 5.2.8 on 2026-01-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_delete_historialempleado'),
        ('inventory', '0007_historialperiferico_periferico_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMovimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Equipo (Histórico)')),
                ('equipo_serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial del Equipo (Histórico)')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('observacion_devolucion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('es_baja', models.BooleanField(default=False, verbose_name='Fue dado de baja')),
                ('fecha_baja', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('empleado_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado', verbose_name='Empleado Asignado')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos', to='inventory.equipo')),
            ],
            options={
                'verbose_name': 'Historial de Movimiento de Equipo',
                'verbose_name_plural': 'Historial de Movimientos de Equipos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
