# Generated by Django 5.2.8 on 2026-01-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_historialmovimientoequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
