# Generated by Django 5.2.8 on 2026-01-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_licencia_fecha_vencimiento'),
        ('sede', '0003_delete_historialsede'),
    ]

    operations = [
        migrations.AddField(
            model_name='periferico',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perifericos', to='sede.sede', verbose_name='Sede'),
        ),
    ]
