# Generated by Django 5.2.8 on 2026-01-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_sede_to_periferico'),
        ('sede', '0003_delete_historialsede'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos_equipos', to='sede.sede', verbose_name='Sede'),
        ),
    ]
