# Generated by Django 5.2.8 on 2026-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_sede_to_pasisalvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos_fotos/', verbose_name='Fotografía del Equipo'),
        ),
    ]
