# Generated by Django 5.2.8 on 2026-02-02 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_sede'),
        ('inventory', '0013_equipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_recepcion_custodia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción en Custodia'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='notas_custodia',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de Custodia'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='responsable_custodia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_bajo_custodia', to='empleados.empleado', verbose_name='Responsable de Custodia Temporal'),
        ),
    ]
