# Generated by Django 5.2.8 on 2026-02-02 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_sede'),
        ('inventory', '0014_equipo_fecha_recepcion_custodia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasisalvo',
            name='firma_recibido',
            field=models.TextField(blank=True, null=True, verbose_name='Firma de quien recibe'),
        ),
        migrations.AddField(
            model_name='pasisalvo',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasisalvos_recibidos', to='empleados.empleado', verbose_name='Recibido por (Custodio)'),
        ),
    ]
