# Generated by Django 5.2.8 on 2026-02-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_pasisalvo_firma_recibido_pasisalvo_recibido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='procesador_historico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador (Histórico)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='ram_historica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RAM (Histórica)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='rom_historica',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ROM (Histórica)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='sistema_operativo_historico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='S.O. (Histórico)'),
        ),
    ]
