# Generated by Django 5.2.8 on 2026-02-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_historialmovimientoequipo_procesador_historico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmovimientoequipo',
            name='procesador_historico',
        ),
        migrations.RemoveField(
            model_name='historialmovimientoequipo',
            name='ram_historica',
        ),
        migrations.RemoveField(
            model_name='historialmovimientoequipo',
            name='rom_historica',
        ),
        migrations.RemoveField(
            model_name='historialmovimientoequipo',
            name='sistema_operativo_historico',
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='antivirus_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Antivirus (Entrega)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='estado_fisico_devolucion',
            field=models.TextField(blank=True, null=True, verbose_name='Estado Físico (Entrada/Recibo)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='estado_fisico_entrega',
            field=models.TextField(blank=True, null=True, verbose_name='Estado Físico (Entrega/Salida)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='estado_tecnico_entrega',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Técnico (Entrega)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='procesador_devolucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador (Devolución)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='procesador_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador (Entrega)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='ram_devolucion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RAM (Devolución)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='ram_entrega',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RAM (Entrega)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='redes_conectadas_entrega',
            field=models.TextField(blank=True, null=True, verbose_name='Redes (Entrega)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='rom_devolucion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Disco (Devolución)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='rom_entrega',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Disco (Entrega)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='so_devolucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='S.O. (Devolución)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='so_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='S.O. (Entrega)'),
        ),
        migrations.AddField(
            model_name='historialmovimientoequipo',
            name='usuarios_sistema_entrega',
            field=models.TextField(blank=True, null=True, verbose_name='Usuarios Sistema (Entrega)'),
        ),
        migrations.AlterField(
            model_name='historialmovimientoequipo',
            name='observacion_devolucion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Generales'),
        ),
    ]
