# Generated by Django 5.2.8 on 2026-02-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_historialmovimientoequipo_procesador_historico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado_fisico',
            field=models.TextField(blank=True, null=True, verbose_name='Estado Físico Actual (Detalles estéticos/golpes)'),
        ),
    ]
