# Generated by Django 5.2.8 on 2026-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_equipo_estado_fisico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasisalvo',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='pasisalvo',
            name='pdf_archivo',
            field=models.FileField(blank=True, help_text='Archivo PDF del pasisalvo generado.', null=True, upload_to='pasisalvos_pdfs/'),
        ),
    ]
