# Generated by Django 5.2.8 on 2026-01-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0002_historialsede'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialSede',
        ),
    ]
